language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi

before_script:
  - composer install --prefer-source

script: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != "hhvm" && "$TRAVIS_PHP_VERSION" != 7* ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi;'
