language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi

before_script:
  - composer install --prefer-source

script: ./vendor/bin/phpunit
